name: Generate Snake Animation

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:  # allows manual runs too

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate github-contribution-grid-snake.svg

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: rk0010dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
